apiVersion: v1
data:
  alertmanager.yml: "global: \n  smtp_smarthost: '<YOUR_SMTP_SERVER>'\n  smtp_from:
    '<YOUR_SMTP_USERNAME>'\n  smtp_auth_username: '<YOUR_SMTP_USERNAME>'\n  smtp_auth_password:
    '<YOUR_SMTP_PASSWORD>'\nreceivers:\n- name: opsmx_alert_receivers\n  email_configs:\n  - to:
    no-reply-demo@opsmx.io\n    send_resolved: false\n    text: \" \\nsummary: {{
    .CommonAnnotations.summary }}\\ndescription: {{ .CommonAnnotations.description
    }}\" \n  slack_configs:\n  - api_url: <SLACK_WEBHOOK_URL>\n    send_resolved:
    true\n    #title: '{{.CommonAnnotations.summary}}'\n    #channel: 'prom-alert-test'\n
    \   #text: '{{ .CommonAnnotations.description }}'\n    text: \"{{ range .Alerts
    }}<!channel> {{ .Annotations.summary }}\\n{{ .Annotations.description }}\\n{{
    end }}\"\n    #title: \"{{ range .Alerts }}{{ .Annotations.summary }}\\n{{ end
    }}\"\n    #text: \"{{ range .Alerts }}{{ .Annotations.description }}\\n{{ end
    }}\"\n    #text: \"<!channel> \\nsummary: {{ .CommonAnnotations.summary }}\\ndescription:
    {{ .CommonAnnotations.description }}\" \n- name: opsmx_email_only\n  email_configs:\n
    \ - to: no-reply-demo@opsmx.io\n    send_resolved: false\n    text: \" \\nsummary:
    {{ .CommonAnnotations.summary }}\\ndescription: {{ .CommonAnnotations.description
    }}\" \nroute:\n  group_by: [ 'alertname', 'service' ]\n  group_interval: 5m #
    Changed from 5m\n  group_wait: 5ms\n  repeat_interval: 3h # Was set to 3h, changed
    for testing\n  receiver: opsmx_alert_receivers\n  routes:\n  - match: \n      severity:
    warning\n    receiver: opsmx_alert_receivers\n    #receiver: opsmx_email_only\n"
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    chart: prometheus-11.16.2
    component: alertmanager
    heritage: Helm
    release: prom
  name: prom-prometheus-alertmanager
  namespace: oes
