apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  labels:
    app: prometheus
    chart: prometheus-11.16.2
    component: alertmanager
    heritage: Helm
    release: prom
  name: prom-prometheus-alertmanager
  namespace: oes
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: default
  volumeMode: Filesystem
  volumeName: <Your-PV-Name>
